github:
  environments:
    release:
      required_reviewers:
        - id: grails-committers
          type: Team
        - id: jdaugherty
          type: User
      wait_timer: 0
    docs:
      required_reviewers:
        - id: grails-committers
          type: Team
        - id: jdaugherty
          type: User
      wait_timer: 0
